---
- name: download rust binary
  get_url: url="http://static.rust-lang.org/dist/{{ rust_download_name }}.tar.gz"
           dest="~/{{ rust_download_name }}.tar.gz"

- name: unpack the rust binary
  command: tar -xzvf {{ rust_download_name }}.tar.gz
           chdir="~"
           creates="~/{{ rust_download_name }}"

- name: install rust
  sudo: true
  command: sh install.sh
           chdir="/home/{{ ansible_ssh_user }}/{{ rust_download_name }}"
           creates="/usr/local/bin/rustc"

- name: download cargo source
  git: repo="https://github.com/rust-lang/cargo"
       dest="~/cargo"
       update=false

- name: compile cargo
  command: make
           chdir="~/cargo"
           creates="~/cargo/target/cargo"

- name: install cargo
  sudo: true
  command: make install
           chdir="/home/{{ ansible_ssh_user }}/cargo"
           creates="/usr/local/bin/cargo"
